### ISSUE TITLE
Optional User Authentication

### ISSUE THREAD

**Issue by camjac251** [Arcanemagus/plexWatchWeb#6]
I currently have http authentication set on my plexwatch web but I use a password manager that doesn't support http authentication. Would it be possible to incorporate an html type login with fields? And a remember me as well.

**Comment by Arcanemagus** [comment]
This is already reported in the base project here: https://github.com/ecleese/plexWatchWeb/issues/37 :wink:

**Comment by camjac251** [comment]
But I can't use http authentication

**Comment by Arcanemagus** [comment]
That issue is just "support generic user auth", not necessarily HTTP auth. There are several things I want to work on before I try tackling user authentication on this so discussion on it might as well be on the project where everyone is following it.
